// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc2dxEWfptAI-XULrHkFw3CUHH5KUsCD8',
    appId: '1:1049002475017:web:c902f37807bdeaa36d82d8',
    messagingSenderId: '1049002475017',
    projectId: 'gatorroundup',
    authDomain: 'gatorroundup.firebaseapp.com',
    storageBucket: 'gatorroundup.appspot.com',
    measurementId: 'G-HPM9RYH2R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEyTmJi1prta7PYFjHJilMsnKn4_Zkxs',
    appId: '1:1049002475017:android:a8369d4dd19fcb896d82d8',
    messagingSenderId: '1049002475017',
    projectId: 'gatorroundup',
    storageBucket: 'gatorroundup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABz8xU-GnuN0a2nm6-1_8CUPs7Ki7yn-o',
    appId: '1:1049002475017:ios:f87cd50da999bd906d82d8',
    messagingSenderId: '1049002475017',
    projectId: 'gatorroundup',
    storageBucket: 'gatorroundup.appspot.com',
    iosClientId: '1049002475017-dd7ebcjr7hdu00p16usglio532hvvs3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatorRoundUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABz8xU-GnuN0a2nm6-1_8CUPs7Ki7yn-o',
    appId: '1:1049002475017:ios:f87cd50da999bd906d82d8',
    messagingSenderId: '1049002475017',
    projectId: 'gatorroundup',
    storageBucket: 'gatorroundup.appspot.com',
    iosClientId: '1049002475017-dd7ebcjr7hdu00p16usglio532hvvs3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatorRoundUp',
  );
}
